services:

  app:
    build: .
    environment:
      - IMAP_HOST=${IMAP_HOST}
      - SMTP_HOST=${SMTP_HOST}
    init: true
    ports:
      - "${HERMES_PORT:-8143}:8143"
    restart: unless-stopped
