services:

  app:
    build: .
    environment:
      - HERMES_HOST_IMAP=${HERMES_HOST_IMAP}
      - HERMES_HOST_SMTP=${HERMES_HOST_SMTP}
      - HERMES_PORT=${HERMES_PORT:-8143}
    init: true
    ports:
      - "${HERMES_PORT:-8143}:${HERMES_PORT:-8143}"
    restart: unless-stopped
